TYPO3:
  Flow:
    security:
      authentication:
        providers:
          Typo3BackendProvider:
            provider: '\CM\Neos\Yubico\Authentication\Provider\PersistedUsernamePasswordProvider'
            tokenClass: '\CM\Neos\Yubico\Authentication\Token\UsernamePassword'

CM:
  Flow:
    Yubico:
      api:
        clientId: 'add-your-client-id'
        secretKey: 'add-your-secret-key'